services:
  portfolio:
    image: portfolio
    build:
      context: .
      dockerfile: Portfolio/Dockerfile
    container_name: portfolio
    volumes:
      - ${PORTFOLIO_FILES_DIRECTORY}:/Files
    expose:
      - "8080"
    environment:
      - PORTFOLIO_MAIL_HREF=${PORTFOLIO_MAIL_HREF}
      